venteachat:
     resource: "@venteachatBundle/Resources/config/routing.yml"
     prefix:   /{_locale}/
     requirements: 
        _locale: en|fr|

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"